spring:
  datasource:
    url: jdbc:postgresql://34.93.89.66:5432/student-management-system
    username: postgres
    password: Chamath@123
    driver-class-name: org.postgresql.Driver

# Storage mode: 'gcs' uses Google Cloud Storage bucket
app:
  storage:
    mode: gcs
    gcs:
      bucket-name: cloud-storage-bucket-student-management-system
      credentials-path: classpath:enterprise-cloud-architecture-310789e4e6e6.json
